### ISSUE TITLE
Error in Example with California Housing Dataset

### ISSUE THREAD

**Issue by sergulaydore** [kathrinse/be_great#14]
Hi,

I have been trying to reproduce your results, and got an error with the example in your [repo](https://github.com/kathrinse/be_great/blob/main/examples/Example_California_Housing.ipynb).
The code I try to run is as below:
```
from be_great import GReaT
from sklearn import datasets

data = datasets.fetch_california_housing(as_frame=True).frame
great = GReaT("distilgpt2",                         # Name of the large language model used (see HuggingFace for more options)
              epochs=1,                             # Number of epochs to train (only one epoch for demonstration)
              save_steps=2000,                      # Save model weights every x steps
              logging_steps=50,                     # Log the loss and learning rate every x steps
              experiment_dir="trainer_california",  # Name of the directory where all intermediate steps are saved
              #lr_scheduler_type="constant",        # Specify the learning rate scheduler
              #learning_rate=5e-5                   # Set the inital learning rate
             )
trainer = great.fit(data)
```
And I get the error
```
File "/Users/saydore/Documents/projects/SDG_2022/SD_sergul_coding/main.py", line 15, in <module>
    trainer = great.fit(data)
  File "/usr/local/lib/python3.9/site-packages/be_great/great.py", line 114, in fit
    great_trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/usr/local/lib/python3.9/site-packages/transformers/trainer.py", line 1633, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.9/site-packages/transformers/trainer.py", line 1872, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 56, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/usr/local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2662, in __getitems__
    batch = self.__getitem__(keys)
  File "/usr/local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2658, in __getitem__
    return self._getitem(key)
  File "/usr/local/lib/python3.9/site-packages/be_great/great_dataset.py", line 31, in _getitem
    row = self._data.fast_slice(key, 1)
  File "/usr/local/lib/python3.9/site-packages/datasets/table.py", line 135, in fast_slice
    if offset < 0:
TypeError: '<' not supported between instances of 'list' and 'int'
  0%|          | 0/2580 [00:00<?, ?it/s]
```
Could you please help me resolve this issue?

**Comment by unnir** [comment]
Hi,

Sorry about that. 

This error is due to the update of the huggingsface package datasets.
To avoid it please do:

```
pip install datasets==2.5.2
```

**Comment by sergulaydore** [comment]
Thank you for your response. It works not with the california housing data set. But, I could not make it work for adult.

```
from sklearn.datasets import fetch_openml
from be_great import GReaT

data = fetch_openml('adult', as_frame=True).frame
great = GReaT("distilgpt2",                         # Name of the large language model used (see HuggingFace for more options)
              epochs=1,                             # Number of epochs to train (only one epoch for demonstration)
              save_steps=2000,                      # Save model weights every x steps
              logging_steps=50,                     # Log the loss and learning rate every x steps
              experiment_dir='adult',  # Name of the directory where all intermediate steps are saved
              #lr_scheduler_type="constant",        # Specify the learning rate scheduler
              #learning_rate=5e-5                   # Set the inital learning rate
             )
trainer = great.fit(data)
```
I get the following error
```
Traceback (most recent call last):
  File "/Users/saydore/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4345.23/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 9, in <module>
  File "/usr/local/lib/python3.9/site-packages/be_great/great.py", line 100, in fit
    great_ds = GReaTDataset.from_pandas(df)
  File "/usr/local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 830, in from_pandas
    return cls(table, info=info, split=split)
  File "/usr/local/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 676, in __init__
    inferred_features = Features.from_arrow_schema(arrow_table.schema)
  File "/usr/local/lib/python3.9/site-packages/datasets/features/features.py", line 1569, in from_arrow_schema
    obj = {field.name: generate_from_arrow_type(field.type) for field in pa_schema}
  File "/usr/local/lib/python3.9/site-packages/datasets/features/features.py", line 1569, in <dictcomp>
    obj = {field.name: generate_from_arrow_type(field.type) for field in pa_schema}
  File "/usr/local/lib/python3.9/site-packages/datasets/features/features.py", line 1313, in generate_from_arrow_type
    raise NotImplementedError  # TODO(thom) this will need access to the dictionary as well (for labels). I.e. to the py_table
NotImplementedError
```
Could you share your implementation for adult or let me know what I am doing wrong here?

**Comment by unnir** [comment]
I'm glad it worked for you! 

For how many epochs do you fine-tuning?
